version: "3.7"

services:
  frontend:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    build:
      context: ./frontend
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - network_a
      - network_b

  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - network_b

  backend:
    image: node:12.18.1
    command: sh -c "yarn install && node server.js"
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    working_dir: /backend
    networks:
      - network_a
      - network_b
  nginx:
    image: nginx
    volumes:
      - ./reverseProxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - network_a
volumes:
  todo-mysql-data:

networks:
  network_a:
    driver: bridge
  network_b:
    driver: bridge
